name: DEPLOY

on:
    push:
        tags:
            - 'v*'

env:
    FORCED_VERSION: ${{ github.ref }}
    BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
    BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
    ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
    SONATYPE_USERNAME: ${{ secrets.SONATYPEUSERNAME }}
    SONATYPE_PASSWORD: ${{ secrets.SONATYPEPASSWORD }}

jobs:
    publish-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v1
            - run: >
                CALL gradlew.bat --no-daemon
                jvmTest
                publishMingwX64PublicationToMavenRepository
              shell: cmd
              env:
                  DISABLE_JAVASCRIPT_TEST: true
    publish-mac:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v1
            - run: >
                ./gradlew
                jvmTest
                publishMacosX64PublicationToMavenRepository
                publishMacosArm64PublicationToMavenRepository
                publishIosArm32PublicationToMavenRepository
                publishIosArm64PublicationToMavenRepository
                publishIosX64PublicationToMavenRepository
                publishIosSimulatorArm64PublicationToMavenRepository
                publishWatchosX86PublicationToMavenRepository
                publishWatchosArm32PublicationToMavenRepository
                publishWatchosArm64PublicationToMavenRepository
                publishWatchosSimulatorArm64PublicationToMavenRepository
                publishTvosX64PublicationToMavenRepository
                publishTvosArm64PublicationToMavenRepository
                publishTvosSimulatorArm64PublicationToMavenRepository
              env:
                  DISABLE_JAVASCRIPT_TEST: true
    publish-linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: sudo apt-get install xvfb
            - run: >
                xvfb-run --auto-servernum ./gradlew --no-daemon
                jvmTest
                publishKotlinMultiplatformPublicationToMavenRepository
                publishJvmPublicationToMavenRepository
                publishJsPublicationToMavenRepository
                publishAndroidPublicationToMavenRepository
                publishLinuxX64PublicationToMavenRepository
    publish-finalize:
        needs: [publish-windows, publish-mac, publish-linux]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: ./gradlew releaseMavenCentral
